Repository readmeio/oas-to-har, pull requests merged in 2022-04, with the labels that each got.

#76 fix: support for allowReserved
  __tests__/lib/style-formatting/index.test.js
  src/lib/style-formatting/index.js
  src/lib/style-formatting/style-serializer.js
Labels: enhancement

#77 fix: support for multi-level deepObjects
  __tests__/__fixtures__/create-oas.js
  __tests__/__fixtures__/style-data.js
  __tests__/lib/style-formatting/index.test.js
  __tests__/lib/style-formatting/multipart-form-data.test.js
  package-lock.json
  package.json
  src/lib/style-formatting/index.js
  src/lib/style-formatting/style-serializer.js
Labels: enhancement

#78 feat: browser testing!
  .alexignore
  .alexrc
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  .mocharc.json
  .npmignore
  __tests__/.eslintrc
  __tests__/auth.test.js
  __tests__/index.test.js
  __tests__/lib/style-formatting/index.test.js
  __tests__/parameters.test.js
  __tests__/requestBody.test.js
  karma.conf.js
  package-lock.json
  package.json
  test/.eslintrc
  test/__datasets__/common-parameters.json
  test/__datasets__/formData-nested-object.json
  test/__datasets__/multipart-form-data.json
  test/__datasets__/multipart-form-data/array-of-files.json
  test/__datasets__/owlbert.dataurl.json
  test/__datasets__/owlbert.png
  test/__datasets__/requestBody-raw_body.json
  test/__datasets__/security.json
  test/__datasets__/server-variables.json
  test/__fixtures__/create-oas.js
  test/__fixtures__/style-data.js
  test/auth.test.js
  test/helpers/chai-plugins.js
  test/index.test.js
  test/lib/configure-security.test.js
  test/lib/style-formatting/index.test.js
  test/lib/style-formatting/multipart-form-data.test.js
  test/parameters.test.js
  test/requestBody.test.js
Labels: enhancement, refactor

#79 fix: code cleanup
  LICENSE
  README.md
  src/index.js
  src/lib/style-formatting/index.js
  src/lib/style-formatting/style-serializer.js
Labels: refactor

#80 fix: issue where a lowercase `Accept` header may be duplicated
  src/index.js
  test/parameters.test.js
Labels: bug

#81 feat: adding support for RAW_BODY payloads when not on JSON-like content types
  src/index.js
  test/__datasets__/requestBody-raw_body.json
  test/requestBody.test.js
Labels: bug

#82 chore(deps): bumping deps to resolve node 18 compat warnings
  package-lock.json
  package.json
Labels: enhancement
