Repository readmeio/oas-to-har, pull requests merged in 2022-02, with the labels that each got.

#58 feat: upgrading oas and replacing some deprecated accessors
  __tests__/index.test.js
  __tests__/parameters.test.js
  package-lock.json
  package.json
  src/index.js
Labels: enhancement, refactor

#59 feat: moving to our new remove-undefined-objects package
  __tests__/lib/remove-undefined-objects.test.js
  package-lock.json
  package.json
  src/index.js
  src/lib/remove-undefined-objects.js
Labels: refactor

#60 feat(styles): add space and pipe delimited support for objects per 3.1
  __tests__/lib/style-formatting/index.test.js
  src/lib/style-formatting/style-serializer.js
Labels: enhancement
