Repository readmeio/oas-to-har, pull requests merged in 2023-09, with the labels that each got.

#236 feat(esm): upgrading oas tooling deps for esm support
  package-lock.json
  package.json
  src/index.ts
  src/lib/configure-security.ts
  src/lib/style-formatting/index.ts
  src/lib/utils.ts
  test/__fixtures__/create-oas.ts
  test/lib/configure-security.test.ts
  test/parameters.test.ts
  tsconfig.json
  tsup.config.ts
Labels: enhancement

#240 feat: dropping support for node 16
  .eslintrc
  .github/workflows/ci.yml
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement

#241 fix: split out type exports
  package.json
  src/index.ts
  src/lib/configure-security.ts
  src/lib/types.ts
  tsup.config.ts
Labels: bug, refactor

#242 refactor: use `lodash-es` over `lodash`
  .eslintrc
  package-lock.json
  package.json
  src/index.ts
  src/lib/utils.ts
Labels: dependencies, refactor

#243 fix: don't use module
  src/lib/style-formatting/style-serializer.ts
Labels: bug

#245 revert: bring back old-school lodash
  .eslintrc
  package-lock.json
  package.json
  src/index.ts
  src/lib/utils.ts
Labels: bug

#247 fix: try loading `lodash` exports a different way
  src/index.ts
  src/lib/utils.ts
Labels: bug

#248 fix: another attempt to get lodash working
  .eslintrc
  package-lock.json
  package.json
  src/index.ts
  src/lib/configure-security.ts
  src/lib/style-formatting/index.ts
  src/lib/style-formatting/style-serializer.ts
  src/lib/utils.ts
  test/auth.test.ts
  test/index.test.ts
  test/lib/configure-security.test.ts
  test/lib/style-formatting/index.test.ts
  test/lib/style-formatting/multipart-form-data.test.ts
  test/parameters.test.ts
  test/requestBody.test.ts
Labels: bug
